---

- name: install nginx
  apt: 
    name: nginx
    state: present

- name: unlink default file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent


- name: create own magento conf file
  copy: 
    src: ./files/magento
    dest: /etc/nginx/sites-enabled/magento
  notify: restart nginx

 