---
- name: Install php
  apt: 
    name: 
      - 'php7.4' 
      - 'php7.4-bcmath'
      - 'php7.4-common'
      - 'php7.4-curl' 
      - 'php7.4-fpm'
      - 'php7.4-gd'
      - 'php7.4-intl'
      - 'php7.4-mbstring'
      - 'php7.4-mysql'
      - 'php7.4-soap'
      - 'php7.4-xml'
      - 'php7.4-xsl'
      - 'php7.4-zip'
      - 'php7.4-cli'
    state: present

- name: shell commands
  shell: |
    sed -i "s/memory_limit = .*/memory_limit = 768M/" /etc/php/7.4/fpm/php.ini
    sed -i "s/upload_max_filesize = .*/upload_max_filesize = 128M/" /etc/php/7.4/fpm/php.ini
    sed -i "s/zlib.output_compression = .*/zlib.output_compression = on/" /etc/php/7.4/fpm/php.ini
    sed -i "s/max_execution_time = .*/max_execution_time = 18000/" /etc/php/7.4/fpm/php.ini
  notify: restart php